version: '3.8'

services:
  # EHR Portal Web Application
  ehr-portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ehr-portal
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - ehr-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: FHIR Server (for production use)
  # Uncomment if you need a FHIR backend server
  # fhir-server:
  #   image: hapiproject/hapi:latest
  #   container_name: ehr-fhir-server
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fhir
  #     - SPRING_DATASOURCE_USERNAME=fhir
  #     - SPRING_DATASOURCE_PASSWORD=fhir
  #     - HAPI_FHIR_VERSION=R4
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #   networks:
  #     - ehr-network

  # Optional: PostgreSQL Database
  # Uncomment if you need a database for FHIR server
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: ehr-postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=fhir
  #     - POSTGRES_USER=fhir
  #     - POSTGRES_PASSWORD=fhir
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - ehr-network

networks:
  ehr-network:
    driver: bridge

# Optional: Volumes for persistent data
# volumes:
#   postgres-data:
#     driver: local
