version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ehr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ehr_user
      POSTGRES_PASSWORD: ehr_password
      POSTGRES_DB: ehr_portal
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ehr_user -d ehr_portal']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ehr-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://ehr_user:ehr_password@postgres:5432/ehr_portal?schema=public
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRATION: 1d
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-this-in-production
      JWT_REFRESH_EXPIRATION: 7d
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - /app/node_modules

volumes:
  postgres_data:
